#!/bin/bash

WDIR=$(readlink -m `pwd`/..)

PKG_PREFIX=plumgrid-sigmund
PKG_DESCRIPTION="SIGnatures Monitor and UNifier Daemon"
PKG_ARCH="amd64"
. ${WDIR}/pkg/deb-functions.sh

# determine version
compute_deb_version

# trap keyboard interrupt (control-c)
trap control_c SIGINT

rm -f ${WDIR}/${PKG_PREFIX}_*.deb

BDIR_BASE=${WDIR}/${PKG_PREFIX}_${PG_DEBVERSION}_${PKG_ARCH}
rm -rf ${BDIR_BASE}

## copy all files to their destination
# binaries
mkdir -p ${BDIR_BASE}/usr/bin/
cp ${WDIR}/src/sigmund ${BDIR_BASE}/usr/bin/sigmund
strip ${BDIR_BASE}/usr/bin/sigmund
cp ${WDIR}/../src/sigmund-configure ${BDIR_BASE}/usr/bin/sigmund-configure
# configuration files
mkdir -p ${BDIR_BASE}/etc/sigmund/
cp ${WDIR}/../conf/sigmund.conf.example ${BDIR_BASE}/etc/sigmund/sigmund.conf.example
# service files
mkdir -p ${BDIR_BASE}/etc/init/
cp ${WDIR}/../init/plumgrid-sigmund.conf ${BDIR_BASE}/etc/init/plumgrid-sigmund.conf
cp ${WDIR}/../init/plumgrid-sigmund.override ${BDIR_BASE}/etc/init/plumgrid-sigmund.override
# documentation/example files
mkdir -p ${BDIR_BASE}/usr/share/doc/sigmund-${PG_DEBVERSION}/kibana-dashboards/
cp ${WDIR}/../misc/kibana-dashboards/export.json ${BDIR_BASE}/usr/share/doc/sigmund-${PG_DEBVERSION}/kibana-dashboards/export.json
#####################################

PKG_DEPS="libsqlite3-0, libcurl3, libprotobuf7, bash, grep, sed"

gen_control_file  "${PKG_PREFIX}"  "${PG_DEBVERSION}"  "${PKG_ARCH}" "${PKG_DESCRIPTION}" "${PKG_DEPS}"

build_package
status=$?

rm -rf ${BDIR_BASE}
echo "Package build exiting with status: ${status}"
exit $status
